FROM node:alpine

# USER node

# RUN mkdir -p /home/node/app
# WORKDIR /home/node/app
WORKDIR /usr/app

# COPY --chown=node:node ./package.json ./
COPY ./package.json ./
RUN npm install
# COPY --chown=node:node ./ ./ 
COPY ./ ./ 

CMD ["npm", "run", "start"]